image: openjdk:8

variables:
  NAME: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_BUILD_REF_NAME}"
  PROJECTNAME: ConvexMerger

before_script:
  - java -version
  - chmod -R 755 ./*
  - cd ${PROJECTNAME}
  - ls -l

stages:
  - check
  - compile
  - test
  - status
  - javadoc

endings:
  allow_failure: true
  script: curl ${SERVER}ci/lf.sh | bash
  stage: check

pending:
  allow_failure: true
  script: curl ${SERVER}ci/pending.sh | bash
  stage: compile

success:
  allow_failure: true
  script: curl ${SERVER}ci/success.sh | bash
  when: on_success
  stage: status

failure:
  allow_failure: true
  script: curl ${SERVER}ci/failure.sh | bash
  when: on_failure
  stage: status

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script: curl ${SERVER}ci/documentation.sh | bash
  stage: javadoc
  artifacts:
    name: "${NAME} [Javadoc]"
    expire_in: 1 week
    paths:
      - javadoc/

compile:
  script: 
    - ./gradlew shadowJar
    - ./gradlew createExe
    - mv ./build/libs/* ../
    - mv ./build/launch4j/*.exe ../
  stage: compile
  artifacts:
    name: "${NAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}-*.jar
      - ${PROJECTNAME}-*.exe

test:
  script:
    - ./gradlew :test :jacocoTestReport
    - cat ./build/reports/jacoco/test/html/index.html
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: ./${PROJECTNAME}/build/test-results/test/TEST-*.xml